version: '2.2'  # Use a compatible version depending on your Docker Compose installation

services:
  postgres:
    image: postgres:15.3-bullseye  # Specify the PostgreSQL version you need
    container_name: postgres_container
    ports:
      - "5432:5432"  # Map the default PostgreSQL port from the container to the host
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: postgres       # Set the default database name
      POSTGRES_USER: root           # Set the default username
      POSTGRES_PASSWORD: rootpassword   # Set the default password
#    restart: always
#    command: ["postgres", "-c", "max_connections=100"]

volumes:
  db-data:  # Declar